export const COLOUR_TOKENS = [
  { token: 'diamond', system: 'sequential', lightHex: '#5B9BD5', darkHex: '#2E78C4' },
  { token: 'platinum', system: 'sequential', lightHex: '#B8E0FF', darkHex: '#5BA4D4' },
  { token: 'gold', system: 'sequential', lightHex: '#F4C430', darkHex: '#D4A017' },
  { token: 'silver', system: 'sequential', lightHex: '#A8B2BE', darkHex: '#6B7280' },
  { token: 'bronze', system: 'sequential', lightHex: '#B87333', darkHex: '#C87941' },
  { token: 'iron', system: 'sequential', lightHex: '#5C3D4A', darkHex: '#5C3D4A' },
  { token: 'ash', system: 'sequential', lightHex: '#D1D5DB', darkHex: '#8A8F9A' },
  { token: 'pos-2', system: 'semantic', lightHex: '#2F9E44', darkHex: '#2F9E44' },
  { token: 'pos-1', system: 'semantic', lightHex: '#94D82D', darkHex: '#74C69D' },
  { token: 'mid', system: 'semantic', lightHex: '#FCC419', darkHex: '#FCC419' },
  { token: 'neg-1', system: 'semantic', lightHex: '#F76707', darkHex: '#F76707' },
  { token: 'neg-2', system: 'semantic', lightHex: '#C92A2A', darkHex: '#C92A2A' },
  { token: 'green-0', system: 'hue', lightHex: '#EBFBEE', darkHex: '#EBFBEE' },
  { token: 'green-1', system: 'hue', lightHex: '#D3F9D8', darkHex: '#D3F9D8' },
  { token: 'green-2', system: 'hue', lightHex: '#B2F2BB', darkHex: '#B2F2BB' },
  { token: 'green-3', system: 'hue', lightHex: '#8CE99A', darkHex: '#8CE99A' },
  { token: 'green-4', system: 'hue', lightHex: '#69DB7C', darkHex: '#69DB7C' },
  { token: 'green-5', system: 'hue', lightHex: '#51CF66', darkHex: '#51CF66' },
  { token: 'green-6', system: 'hue', lightHex: '#40C057', darkHex: '#40C057' },
  { token: 'green-7', system: 'hue', lightHex: '#2F9E44', darkHex: '#2F9E44' },
  { token: 'green-8', system: 'hue', lightHex: '#2B8A3E', darkHex: '#2B8A3E' },
  { token: 'green-9', system: 'hue', lightHex: '#1D6B32', darkHex: '#1D6B32' },
  { token: 'blue-0', system: 'hue', lightHex: '#E7F5FF', darkHex: '#E7F5FF' },
  { token: 'blue-1', system: 'hue', lightHex: '#D0EBFF', darkHex: '#D0EBFF' },
  { token: 'blue-2', system: 'hue', lightHex: '#A5D8FF', darkHex: '#A5D8FF' },
  { token: 'blue-3', system: 'hue', lightHex: '#74C0FC', darkHex: '#74C0FC' },
  { token: 'blue-4', system: 'hue', lightHex: '#4DABF7', darkHex: '#4DABF7' },
  { token: 'blue-5', system: 'hue', lightHex: '#339AF0', darkHex: '#339AF0' },
  { token: 'blue-6', system: 'hue', lightHex: '#228BE6', darkHex: '#228BE6' },
  { token: 'blue-7', system: 'hue', lightHex: '#1C7ED6', darkHex: '#1C7ED6' },
  { token: 'blue-8', system: 'hue', lightHex: '#1971C2', darkHex: '#1971C2' },
  { token: 'blue-9', system: 'hue', lightHex: '#1864AB', darkHex: '#1864AB' },
  { token: 'magenta-0', system: 'hue', lightHex: '#F8F0FC', darkHex: '#F8F0FC' },
  { token: 'magenta-1', system: 'hue', lightHex: '#F3D9FA', darkHex: '#F3D9FA' },
  { token: 'magenta-2', system: 'hue', lightHex: '#EEBEFA', darkHex: '#EEBEFA' },
  { token: 'magenta-3', system: 'hue', lightHex: '#E599F7', darkHex: '#E599F7' },
  { token: 'magenta-4', system: 'hue', lightHex: '#DA77F2', darkHex: '#DA77F2' },
  { token: 'magenta-5', system: 'hue', lightHex: '#CC5DE8', darkHex: '#CC5DE8' },
  { token: 'magenta-6', system: 'hue', lightHex: '#BE4BDB', darkHex: '#BE4BDB' },
  { token: 'magenta-7', system: 'hue', lightHex: '#AE3EC9', darkHex: '#AE3EC9' },
  { token: 'magenta-8', system: 'hue', lightHex: '#9C36B5', darkHex: '#9C36B5' },
  { token: 'magenta-9', system: 'hue', lightHex: '#862E9C', darkHex: '#862E9C' },
] as const;

export type ColourToken = (typeof COLOUR_TOKENS)[number]['token'];
export const VALID_COLOUR_TOKENS = new Set(COLOUR_TOKENS.map((t) => t.token));
